### ISSUE TITLE
Support bookmarks

### ISSUE THREAD

**Issue by makeworld-the-better-one** [LukeEmmet/GemiNaut#1]
Thanks!

**Comment by LukeEmmet** [comment]
Yes this is something I wanted to do - the changes are pushed to [github here](https://github.com/LukeEmmet/GemiNaut/commit/2f79bb2e9078a5c7cc7c9b35d3fa5903e8d59427). There is a new Bookmarks menu. The underlying format for the bookmark list is....wait for it.... text/gemini of course. These changes will be bundled into the next release.
