### ISSUE TITLE
font rendering/spacing of figlet text banners

### ISSUE THREAD

**Issue by Dr-WaSaBi** [LukeEmmet/GemiNaut#12]
So I'm sure this will need to be renamed to what the real problem is.  But I noticed this evening that when viewing gemini pages in GemiNaut figlet text banners people have made don't display well.  At first I thought it was just my page, but then saw the same thing at other sites.  My guess is it has to do with my terminal using a mono space font.  Which is Cascadia Mono PL.

Obviously, this very low priority.  

My page in GemiNaut
![figlet-text-render](https://user-images.githubusercontent.com/9504206/95523358-6d67cf00-099c-11eb-9c03-55455a9e6dc7.png)

And again in Bombadillo
![bombadill-figlet-text](https://user-images.githubusercontent.com/9504206/95523431-95573280-099c-11eb-92d0-4e1e9f969de9.png)

Hope this helpful.  Please let me know if there is more I can help/test.
Dr-WaSaBi (a.k.a Russ)

**Comment by Dr-WaSaBi** [comment]
Didn't know if theme would effect it.  So tested it in all the themes and got the same results.

**Comment by LukeEmmet** [comment]
this is expected behaviour - if you want a preformatted region, you need to delimit it with three backticks

```
    ____            _       __      _____       ____  _
   / __ \_____     | |     / /___ _/ ___/____ _/ __ )(_)
  / / / / ___/     | | /| / / __ `/\__ \/ __ `/ __  / /
 / /_/ / /  _      | |/ |/ / /_/ /___/ / /_/ / /_/ / /
/_____/_/  (_)     |__/|__/\__,_//____/\__,_/_____/_/
\\\
----------------------------------------------------->>
///
```

Otherwise the content is not sensitive to whitespace

**Comment by Dr-WaSaBi** [comment]
@LukeEmmet ,
Sorry. didn't mean to waste your time. 🤦‍♂️  I wondered if I was doing something wrong, but when I noticed it on others pages (which I'm sure I just copied) then I was like... oh no, it might be a real problem (albeit a small one).

Again, sorry... I'll go study the spec better.. a lot better 
Thank you
Dr W (aka Russ)
