### ISSUE TITLE
Freeze when trying to open a gopher:// link

### ISSUE THREAD

**Issue by finkiki** [LukeEmmet/GemiNaut#13]
GemiNaut 0.8.8 just freeze when I try to open a gopher:// link. It should do something else, like ask which program to choose to open the link.

**Comment by LukeEmmet** [comment]
thanks for the feedback. Yes GemiNaut should open the site. 

Do you get this for every gopher link? Did you try restarting GemiNaut? If it is just a specific URL, can you provide details of a gopher page that causes the problem?

If so, can you confirm whether the utility that gets the gopher content is available - it sometimes gets removed by antivirus utilities. the following executable should be in place: 

C:\Program Files (x86)\MarmaladeFoo software\GemiNaut\GopherGet\gopher-get.exe

**Comment by LukeEmmet** [comment]
In the forthcoming update this should be much improved - now using an internal gopher and gemini handler
