### ISSUE TITLE
Single quote presented as &apos;

### ISSUE THREAD

**Issue by StoyanDimitrov** [LukeEmmet/GemiNaut#15]
This probably belongs to of some of the underlying tools but since I don't know which I'll post it here.

The address of the resource is `gemini://drewdevault.com/` and looking at the title one can observe the issue. The source, at least presented by the application, shows single quote where the &apos; is used.

Since I do not currently have access to gemini server can not currently test for other HTML entities.

**Comment by LukeEmmet** [comment]
For reference, the bug seems to refers to titles on preformatted regions, not the page title, which is constructed from the first page heading, or paragraph, if none. On the referenced page, the preformatted region had a title with quotes in, which was not being correctly displayed in the tooltip.
