### ISSUE TITLE
Update gemget version

### ISSUE THREAD

**Issue by makeworld-the-better-one** [LukeEmmet/GemiNaut#2]
I've just released a new version of gemget, [v1.2.0](https://github.com/makeworld-the-better-one/gemget/releases/tag/v1.2.0). It improves several things, mostly around self-signed certs. So you should be able to not use `--insecure` in your code, and still have downloads work well.

I'd appreciate if you updated the binary in GemiNaut for the next release. Thanks!

**Comment by LukeEmmet** [comment]
Thats great thankyou. this is now included in [recent commit](https://github.com/LukeEmmet/GemiNaut/commit/c52292f9c922e3f63e478bfd7987ad8daef3c968), will be in next public release

**Comment by makeworld-the-better-one** [comment]
Thanks!
