### ISSUE TITLE
Not downloading using gemget

### ISSUE THREAD

**Issue by makeworld-the-better-one** [LukeEmmet/GemiNaut#3]
I don't use GemiNaut (not on Windows), but my friend who does told me then when they tried to download a file from Konpeito it opened up a portal.mozz.us URL. I would expect that Gemget is used to download it, not the portal, is this a bug? It messes things up especially in this case because it seems Konpeito has blocked the proxy.

**Comment by LukeEmmet** [comment]
This is fixed in the latest 0.8.7 release, which allows linked files to be downloaded, and images viewed within GemiNaut. You can define your preferences for downloading files within the settings window.
