### ISSUE TITLE
More .Net runtime dependency issues

### ISSUE THREAD

**Issue by feoh** [LukeEmmet/GemiNaut#33]
I downloaded the latest Geminaut installer, and when I ran it it put up a dialog that said it needed .Net runtime greater than 6.0, so I installed the 7.0.0 via winget, which let me get through the installer.

However when I run Geminaut, I get a dialog saying the app needs the .net runtime, and prompts me to download 6.

When I tried to install 6, it says I already have 7 installed and there is no update path.

Thanks in advance!

**Comment by LukeEmmet** [comment]
try this one - it is a standalone build that should include all its own dependencies. 

http://www.marmaladefoo.com/vanilla/marmaladefoo/uploads/geminaut/GemiNaut_v0.8.14.msi

**Comment by feoh** [comment]
This works great thank you very much! Maybe folks should consider making this the default installer :)

**Comment by jchaves** [comment]
for what's worth, I had the same problems 2 years later: Installer asks for >6 , installed 9. Launching binary it asks for 6

I could, however, install version 6 and get it running without trouble.
