### ISSUE TITLE
Update gemget to v1.5.0

### ISSUE THREAD

**Issue by makeworld-the-better-one** [LukeEmmet/GemiNaut#6]
This brings the `--no-progress-bar` option will will simplify your parsing.

https://github.com/makeworld-the-better-one/gemget/releases/tag/v1.5.0

**Comment by LukeEmmet** [comment]
many thanks for that. I've incorporated this - see https://github.com/LukeEmmet/GemiNaut/commit/511fedb55447853054daa03c5b578218e8b9d3a5
